project: 
  type: website
  output-dir: docs

website:
  title: "Travis Nowak Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: contact.qmd
        text: Contact me!

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

